version: '3.1'
services:
    web:
        image: 'nginx:alpine'
        working_dir: /app
        volumes:
            - './app:/app'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '80:80'

    db:
        image: 'mariadb:latest'
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DB_NAME}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - '${MYSQL_PORT}:3306'

    app:
        build: docker/php-fpm
        working_dir: /app
        volumes:
            - './app:/app'
            - './docker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini'
        extra_hosts:
            - "host.docker.internal:host-gateway"
        depends_on:
            - db
        ports:
            -   '5173:5173'
        environment:
            - MYSQL_HOST=db
            - MYSQL_DATABASE=${MYSQL_DB_NAME}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
